/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   euler2.c                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: fhenrion <fhenrion@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2019/12/25 11:55:07 by fhenrion          #+#    #+#             */
/*   Updated: 2019/12/26 10:31:06 by fhenrion         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

#include <stdio.h>

long	fib(long nb)
{
	static long	cache[200] = {0};
	long		result;

	if (nb < 2)
		return (nb);
	if (cache[nb])
		return (cache[nb]);
	result = fib(nb - 1) + fib(nb - 2);
	cache[nb] = result;
	return (result);
}

int		main(void)
{
	long	value = 33;
	long	sum = 0;
	long	tmp;

	while (value > 0)
	{
		tmp = fib(value);
		if (!(tmp % 2))
			sum += tmp;
		value--;
	}
	printf("result : %li\n", sum);
	return (0);
}